### ISSUE TITLE
New Docs update breaks extension

### ISSUE THREAD

**Issue by vvirtues** [waymondrang/docsafterdark#28] opened 2023-03-07 00:59 UTC
![brave_L0N6WzpND4](https://user-images.githubusercontent.com/81705406/223291357-c8b68e81-52e1-4545-a7fd-40171d9e3577.png)
Google Docs got a new look, which breaks the extension. Above is with DAD disabled, below is with it enabled
![brave_QIkJCcYtXf](https://user-images.githubusercontent.com/81705406/223291619-fc99b720-ccde-4b5c-ae18-1ccdf47aad2d.png)
Hopefully self-explanatory

**Comment by rorybd** [comment] 2023-03-08 17:12
Can also confirm.
![image](https://user-images.githubusercontent.com/124809440/223782154-b908bbb4-e784-4861-8be7-5018b9acc441.png)

**Comment by rorybd** [comment] 2023-03-08 17:13
Can also confirm.
![image](https://user-images.githubusercontent.com/124809440/223782446-afb825ec-b6a0-4ffb-95f4-49321fb05848.png)

**Comment by EpicLiem** [comment] 2023-03-08 23:56
@waymondrang Are you working on this? I can help.

**Comment by waymondrang** [comment] 2023-03-09 03:41
Thank you for opening an issue regarding the UI update to Google Docs. I am aware of the problem and will be releasing an update for it as soon as possible. I appreciate your patience and understanding in this matter.

**Comment by waymondrang** [comment] 2023-03-09 03:51
> @waymondrang Are you working on this? I can help.
> 
> It also seems like the change is being rolled out slowly. The change only appears on one of my Google accounts.

Thank you for your willingness to help with this issue. The issue is already being investigated and a fix is underway.

**Comment by waymondrang** [comment] 2023-03-12 10:20
Many visible issues caused by the Google Docs redesign have been fixed in DocsAfterDark v0.6.0 ([release notes](https://github.com/waymondrang/docsafterdark/releases/tag/v0.6.0)). Please note that it may take several days before the update is finally distributed to users.

**Closed by waymondrang** 2023-03-12 10:20 UTC
Labels: urgent
