### ISSUE TITLE
Search Icon Broken

### ISSUE THREAD

**Issue by rorybd** [waymondrang/docsafterdark#37] opened 2023-07-31 19:30 UTC
The 'Search the menus' icon (leftmost in the menu toolbar) is no longer set to dark mode.
![image](https://github.com/waymondrang/docsafterdark/assets/124809440/02ada9f4-ccf5-4d43-9cf1-259d38d704e6)

**Comment by AIDaN80112** [comment] 2023-09-04 17:55
still happening as of writing, please fix! @waymondrang

**Comment by voytek9** [comment] 2023-09-05 18:17
Only issue keeping me from using this extension!

**Comment by AIDaN80112** [comment] 2023-09-16 18:58
@voytek9 just emailed him as i dont think he checks this & its been quite a long time that this has gone unfixed lol. ill let you know if i hear back

**Comment by waymondrang** [comment] 2023-09-23 20:42
Thank you for opening this issue. This has been addressed in [v0.6.2](https://github.com/waymondrang/docsafterdark/releases/tag/v0.6.2). It may take up to several days for the extension/add-on stores to approve the update. I apologize for the lack of communication and appreciate all of your feedback.

**Closed by waymondrang** 2023-09-23 20:42 UTC
Labels: urgent

**Comment by AIDaN80112** [comment] 2023-09-23 20:45
thank you so much for fixing it! i look forward to receiving the update!! @voytek9 @rorybd ^^

**Comment by AIDaN80112** [comment] 2023-09-23 20:50
1 question (i decided to load unpacked the extension after downloading the zip from the releases page and the search icon is fixed i can confirm)~ will it autoupdate considering i used the load unpacked method? or do i have to switch back to the chrome web store for it to auto update
<img width="1068" alt="image" src="https://github.com/waymondrang/docsafterdark/assets/43555540/cc081dc1-8d58-4aaf-b8ac-873615f63b43">

**Comment by voytek9** [comment] 2023-09-23 21:25
Dude thank you so much, you're a legend!

**Comment by waymondrang** [comment] 2023-09-24 00:32
> 1 question (i decided to load unpacked the extension after downloading the zip from the releases page and the search icon is fixed i can confirm)~ will it autoupdate considering i used the load unpacked method? or do i have to switch back to the chrome web store for it to auto update <img alt="image" width="1068" src="https://user-images.githubusercontent.com/43555540/270132758-cc081dc1-8d58-4aaf-b8ac-873615f63b43.png">

The manually installed version of DocsAfterDark will not automatically update. I would recommend checking the version of the one from the web store and switching over when it's up-to-date. I hope this helps!

**Comment by AIDaN80112** [comment] 2023-09-24 00:35
gotchu. tysm!

**Comment by AIDaN80112** [comment] 2023-09-24 16:54
sorry another question lol. is there any way to get this on safari for macos? i dont wanna use the chrome version because then id have to log into my school account to get it and once i log into my school account they track my activity across any chrome profile which is annoying and i cant remove it so for my privacy i wanna use a diff browser

**Comment by rorybd** [comment] 2023-09-24 16:58
> sorry another question lol. is there any way to get this on safari for macos? i dont wanna use the chrome version because then id have to log into my school account to get it and once i log into my school account they track my activity across any chrome profile which is annoying and i cant remove it so for my privacy i wanna use a diff browser

I don't believe there's a Safari version, but Firefox or other chromium browsers would work just as well.
However, Chrome can also use different profiles, which might be effective in separating administrated accounts from your personal ones.

**Comment by AIDaN80112** [comment] 2023-09-24 17:00
I already have separate chrome profiles for personal and school but on my personal it still says ‘managed by your organization’ the second I add the school profile and it doesn’t go away once I remove the school profile, only way to make it stop tracking me is to restore my Mac to factory settings quite literally lmao

**Comment by dbstone** [comment] 2024-02-03 12:43
This is still broken for me on Chrome. Checking the commit, I see that you only changed docs.css for Opera and Firefox. Is there a reason for this, or did you just forget to include the Chrome version in the fix?

**Comment by ComfortableMilk4454** [comment] 2024-02-03 12:56
its actually broken for me too again on FF.

**Comment by rorybd** [comment] 2024-02-03 13:40
It's possible that Google has recently changed that element again. It is not currently broken for me in Microsoft Edge, but this is more likely to do with staged rollout on Google's end than it is to do with browser.

I believe this would warrant the creation of a new, separate issue due to the nature of the problem.
