### ISSUE TITLE
Explore/Link objects/citations menu is white

### ISSUE THREAD

**Issue by CodeKid2024** [waymondrang/docsafterdark#42] opened 2023-12-06 18:02 UTC
![Screenshot 2023-12-06 130303](https://github.com/waymondrang/docsafterdark/assets/81322639/3ca84e94-7110-419b-976f-8272c0122cfa)

**Comment by waymondrang** [comment] 2024-12-29 00:58
Hello, thank you for opening this issue! However, I will close this issue (even though it is not yet resolved) as it is a duplicate of #40.

**Closed by waymondrang** 2024-12-29 00:58 UTC
Labels: bug
